### PR TITLE
Refactor multiarch support to go all the way to correct Architectures lines in "generate-stackbrew-library.sh"

### PR DESCRIPTION
**Pull request by tianon**
See also docker-library/buildpack-deps#59, docker-library/golang#163, docker-library/docker#63, https://github.com/docker-library/gcc/issues/36, jessfraz/irssi#15, https://github.com/docker-library/redis/pull/95.

### CODE REVIEW

**Comment by tianon** [comment]
This will have better output following https://github.com/docker-library/official-images/pull/3041.

**Comment by tianon** [comment]
This will have better output following https://github.com/docker-library/official-images/pull/3041:
```console
$ ./generate-stackbrew-library.sh
# this file is generated via https://github.com/docker-library/openjdk/blob/efbcd4f8e42e510ef561a7ce518633f0eba33992/generate-stackbrew-library.sh

Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
             Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/openjdk.git

Tags: 6b38-jdk, 6b38, 6-jdk, 6
Architectures: amd64, arm32v7, i386
GitCommit: bd3c2a9867c9dc6a9a8425a8df5c54edf0cbf2cc
Directory: 6-jdk

Tags: 6b38-jre, 6-jre
Architectures: amd64, arm32v7, i386
GitCommit: bd3c2a9867c9dc6a9a8425a8df5c54edf0cbf2cc
Directory: 6-jre

Tags: 7u131-jdk, 7u131, 7-jdk, 7
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 93316d3b14379d29fe0cd363bd6839eb8dd8cc7b
Directory: 7-jdk

Tags: 7u131-jdk-alpine, 7u131-alpine, 7-jdk-alpine, 7-alpine
Architectures: amd64
GitCommit: 43e145f3fc5fd98a141f0c1c6fe90b9ea93977da
Directory: 7-jdk/alpine

Tags: 7u131-jre, 7-jre
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 93316d3b14379d29fe0cd363bd6839eb8dd8cc7b
Directory: 7-jre

Tags: 7u131-jre-alpine, 7-jre-alpine
Architectures: amd64
GitCommit: 43e145f3fc5fd98a141f0c1c6fe90b9ea93977da
Directory: 7-jre/alpine

Tags: 8u131-jdk, 8u131, 8-jdk, 8, jdk, latest
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 415b0cc42d91ef5d70597d8a24d942967728242b
Directory: 8-jdk

Tags: 8u131-jdk-alpine, 8u131-alpine, 8-jdk-alpine, 8-alpine, jdk-alpine, alpine
Architectures: amd64
GitCommit: 43e145f3fc5fd98a141f0c1c6fe90b9ea93977da
Directory: 8-jdk/alpine

Tags: 8u131-jdk-windowsservercore, 8u131-windowsservercore, 8-jdk-windowsservercore, 8-windowsservercore, jdk-windowsservercore, windowsservercore
Architectures: windows-amd64
GitCommit: 9745c87a15896ec558429a826e23926e721e4846
Directory: 8-jdk/windows/windowsservercore
Constraints: windowsservercore

Tags: 8u131-jdk-nanoserver, 8u131-nanoserver, 8-jdk-nanoserver, 8-nanoserver, jdk-nanoserver, nanoserver
Architectures: windows-amd64
GitCommit: 9745c87a15896ec558429a826e23926e721e4846
Directory: 8-jdk/windows/nanoserver
Constraints: nanoserver

Tags: 8u131-jre, 8-jre, jre
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 415b0cc42d91ef5d70597d8a24d942967728242b
Directory: 8-jre

Tags: 8u131-jre-alpine, 8-jre-alpine, jre-alpine
Architectures: amd64
GitCommit: 43e145f3fc5fd98a141f0c1c6fe90b9ea93977da
Directory: 8-jre/alpine

Tags: 9-b170-jdk, 9-b170, 9-jdk, 9
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: c34391ea981c804c097981bad8403ec4bd934285
Directory: 9-jdk

Tags: 9-b170-jre, 9-jre
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: c34391ea981c804c097981bad8403ec4bd934285
Directory: 9-jre
```

**Comment by md5** [comment]
@tianon Do you have any guidance on how to support this in derived images? I'd like to make any changes necessary to the `jetty` image. It looks like we just need to add an `Architectures` line to the library file and update our `generate-stackbrew-library.sh` similar to what was done here?

**Comment by tianon** [comment]
@md5 yeah, if Jetty supports other arches (which would make sense, given its Java base :smile:), adding an appropriate `Architectures` line similar to these should do the trick!  There are a number of good examples now (cross-linked around here, but all linked from https://github.com/docker-library/buildpack-deps/pull/59) which have varying degrees of support for multiarch (either same arches as their parent or a subset) :+1:

(I'd just ask that you test on at least `i386` by modifying your `FROM` locally to include `i386/...` to ensure that at least the _basic_ functionality works on another arch, but preferably test on all the arches you end up including if you can. :sweat_smile:)

**Pull request merged**
