### PR TITLE
Force install nss with openjdk in alpine

### LINKED ISSUE #289: Missing libnss3.so after updating openjdk:8-jdk-alpine image
Hello,

I have a docker file that builds openjdk:8-jdk-alpine based images. When updating the image internally (from the docker file) using `apk update && apk upgrade ` , and running my (spring-boot) app, it throws `java.io.IOException: Error loading shared library libnss3.so: No such file or directory`. However; after removing the `apk update && apk upgrade ` and building the image again, the app runs smoothly. 

I have logged into my images in both cases, and made sure that the file wasn't there on the first case, and was there after removing `apk update && apk upgrade `. In the later case, it was located in `/usr/lib/`

Is this a bug, or can you please inform me of what I might be missing ?

### PR DESCRIPTION
**Pull request by luiszimmermann**
Adding nss to the alpine image

Closes #289

### CODE REVIEW

**Comment by matsewe** [comment]
The problem concerning the jessie-update repository which led to build failures for `VERSION=7` has been fixed; builds should pass now.

**Comment by luiszimmermann** [comment]
Triggering Travis

**Comment by matsewe** [comment]
I guess, another run of `update.sh` should fix this problem. Most recent version of opendjk-7 for `jessie` is, according to `update.sh`, `7u211-2.6.17-1~deb8u1`. This is not yet incorporated into the Dockerfile.

**Comment by tianon** [comment]
I've updated this with the minimal change and cancelled every job on Travis (and AppVeyor) that isn't related to the actual fix, so once https://travis-ci.org/docker-library/openjdk/jobs/512206934 is green we're good to go (assuming @yosifkit approves of my approach).

**Comment by tianon** [comment]
(Then @docker-library-bot will take care of testing and pushing the rest of the updates as appropriate.)

**Comment by tianon** [comment]
Welp, since Travis is having a sad, I've built both of these successfully locally and run the `java-ca-certificates` test directly and they both now pass.

**Comment by J0WI** [comment]
This has been fixed upstream in https://git.alpinelinux.org/aports/commit/?h=3.9-stable&id=87ea954c9b7e200efbb52b4395dfc160fa4f0b55

**Pull request merged**
